# Trystan2k's Brewfile

#Taps
tap "sst/tap"

# Binaries
brew "ack"
brew "antidote"
brew "coreutils"
brew "bat"
brew "curl"
brew "delta"
brew "detox"
brew "dust"
brew "eza"
brew "fd"
brew "fx"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "gum"
brew "httpie"
brew "hub"
brew "hyperfine"
brew "jq"
brew "libyaml"
brew "m-cli"
brew "mas"
brew "mcfly"
brew "mise"
brew "pass"
brew "procs"
brew "ripgrep"
brew "scrcpy"
brew "shellcheck"
brew "subversion"
brew "terminal-notifier"
brew "tree"
brew "wget"
brew "zoxide"
brew "zsh"

# Apps

## Utils
cask "alt-tab"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "deskpad"
cask "hot"
cask "jordanbaird-ice"
brew "killport"
cask "notion"
cask "overkill"
cask "piphero"
cask "raycast"
cask "shottr"
brew "termshot"
brew "trex"

## Dev
cask "bruno"
cask "figma"
brew "gh"
cask "ghostty"

## Editors
cask "sublime-text"
cask "trae"

# Fonts
cask "font-fira-code"
cask "font-hack-nerd-font"

# AI Tools
brew "sst/tap/opencode"