# Trystan2k's Brewfile

# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Binaries
brew "ack"
brew "coreutils"
brew "asdf"
brew "autojump"
brew "bat"
brew "curl"
brew "detox"
brew "exa"
brew "fd"
brew "fx"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "gum"
brew "httpie"
brew "hub"
brew "hyperfine"
brew "jq"
brew "m-cli"
brew "mas"
brew "mcfly"
brew "pass"
brew "plz-cli"
brew "procs"
brew "ripgrep"
brew "scrcpy"
brew "shellcheck"
brew "subversion"
brew "terminal-notifier"
brew "tree"
brew "wget"
brew "zsh"

# Apps

## Utils
cask "alt-tab"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "hot"
cask "hiddenbar"
cask "lulu"
cask "notion"
cask "raycast"
cask "shottr"
brew "homeport/tap/termshot"

## Dev
cask "figma"
cask "hyper"
cask "postman"

## Browsers
cask "firefox"
cask "google-chrome"
cask "microsoft-edge"

## Multimedia
cask "LosslessCut"
cask "blackhole-16ch"

## Editors
cask "sublime-text"
cask "visual-studio-code"

# Fonts
cask "font-fira-code"
cask "font-hack-nerd-font"

# App Store
mas "BetterSnapTool", id: 417375580
