#!/usr/bin/env bash

# File: ~/.config/direnv/direnvrc
#shellcheck source=/dev/null
source "$(asdf which direnv_use_asdf)"

# Uncomment the following line to make direnv silent by default.
export DIRENV_LOG_FORMAT=""