#!/usr/bin/env bash

# File: ~/.config/direnv/direnvrc
#shellcheck source=/dev/null
source "$(asdf direnv hook asdf)"

# Uncomment the following line to make direnv silent by default.
export DIRENV_LOG_FORMAT=""