name: CI-workflow

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shell Lint check
        uses: azohra/shell-linter@latest
      - name: ESLint check
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint:eslint
